[package]
name = "gitweb"
version = "0.1.9"
authors = ["Yoann Fleury <yoann.fleury@yahoo.com>"]
edition = "2018"
description = "Open the current remote repository in your browser"
repository = "https://github.com/yoannfleurydev/gitweb"
homepage = "https://github.com/yoannfleurydev/gitweb"
readme = "README.md"
keywords = ["git", "browser"]
categories = ["command-line-utilities"]
license = "Apache-2.0"
exclude = [
    "docs/",
]

[dependencies]
regex = "1"
structopt = "0.2"
open = "1.2"
git2 = "0.9"
