[package]
name = "gitweb"
version = "0.1.7"
authors = ["Yoann Fleury <yoann.fleury@yahoo.com>"]
edition = "2018"
description = "Open the current remote repository in your browser"
repository = "https://github.com/yoannfleurydev/gitweb"
homepage = "https://github.com/yoannfleurydev/gitweb"
license = "Apache-2.0"

[dependencies]
regex = "1"
structopt = "0.2"
open = "1.2"
git2 = "0.9"
